# Netlify build configuration
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Function configuration
[functions]
  # Increase timeout to 26 seconds (max for free tier)
  timeout = 26

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
