# Netlify build configuration
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Note: Netlify functions are no longer used in this project
# All backend functionality is handled by Appwrite

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200# Force rebuild Wed Aug 20 15:51:15 BST 2025
